services:
  nodejs:
    image: server:1.0.0
    container_name: ${SERVER_HOST}
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server:/server
      - server_node_modules:/server/node_modules
    depends_on:
      postgres:
        condition: service_healthy 
    networks:
      - postgres
      - backend
  postgres:
    image: postgres:1.0.0
    container_name: ${POSTGRES_HOST}
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/database
    command: "-p ${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${POSTGRES_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 0s
    networks:
      - postgres
  pgadmin:
    container_name: ${PGADMIN_HOST}
    image: dpage/pgadmin4:9.1
    env_file: .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - ${PGADMIN_PORT}:80
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres
  caddy:
    container_name: caddy-c
    image: caddy:2.9.1
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - backend
      - postgres
volumes:
  server_node_modules:
  postgres_data:
  pgadmin_data: 
  caddy_data:
  caddy_config:
networks:
  postgres:
    driver: bridge
  backend:
    driver: bridge