### Register web user
POST http://localhost:3000/api/v1/auth/web/register
Content-Type: application/json

{
  "email": "test.tes12t@gmail.com",
  "password": "password123"
}

### Login web user
POST http://localhost:3000/api/v1/auth/web/login
Content-Type: application/json

{
  "email": "test.tes12t@gmail.com",
  "password": "password123"
}

### Register tg user
POST http://localhost:3000/api/v1/auth/tg/register
Content-Type: application/json

{
  "telegramId" : "1232139"
}

### Login tg user
POST http://localhost:3000/api/v1/auth/tg/login
Content-Type: application/json
x-api-key: ab7263555bc20da6dc06b2e9dd4b9c3a79b4ba3770be4311af76bc632cfcd3d2

{
  "telegramId" : 1232139
}

### Read user by id
GET http://localhost:3000/api/users/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJ0ZXN0LnRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzM3MzMyODIwLCJleHAiOjE3MzczMzY0MjB9.LkWk54nXKQw3VRPQev1sQIcUqBJLG0BE3NH_BAUkDzE

### Get brands by years
GET http://localhost:3000/api/v1/brands?year=2010&limit=1&offset=0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidGVsZWdyYW1JZCI6IjEyMzIxMzkiLCJ1c2VySWQiOjIwLCJpYXQiOjE3NDAwODQxNDksImV4cCI6MTc0MDA4Nzc0OX0.4W-Ht6yNL7ccCsm75dU2HdcxzRJHig72DK4LTiPLwS4

### Get models by year
GET http://localhost:3000/api/v1/models?brandId=1&year=2009
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidGVsZWdyYW1JZCI6IjEyMzIxMzkiLCJ1c2VySWQiOjIwLCJpYXQiOjE3NDAwODQxNDksImV4cCI6MTc0MDA4Nzc0OX0.4W-Ht6yNL7ccCsm75dU2HdcxzRJHig72DK4LTiPLwS4

### Create car
POST http://localhost:3000/api/v1/cars
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidGVsZWdyYW1JZCI6IjEyMzIxMzkiLCJ1c2VySWQiOjIwLCJpYXQiOjE3Mzc5MjY0ODYsImV4cCI6MTczNzkzMDA4Nn0.y1qbqZwFGp2sCeIqQpjeQze1col1UKcDzNjBKLtpeRU

{
  "modelId" : 1,
  "year" : 2012,
  "miliage" : 280000,
  "vin" : "WVWZZZ1KZA9938772"
}

### Delete a car
DELETE http://localhost:3000/api/v1/cars/16
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidGVsZWdyYW1JZCI6IjEyMzIxMzkiLCJ1c2VySWQiOjIwLCJpYXQiOjE3Mzc5MjY0ODYsImV4cCI6MTczNzkzMDA4Nn0.y1qbqZwFGp2sCeIqQpjeQze1col1UKcDzNjBKLtpeRU

### Get user owned cars
GET http://localhost:3000/api/v1/cars?offset=10
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidGVsZWdyYW1JZCI6IjEyMzIxMzkiLCJ1c2VySWQiOjIwLCJpYXQiOjE3NDAwODQxNDksImV4cCI6MTc0MDA4Nzc0OX0.4W-Ht6yNL7ccCsm75dU2HdcxzRJHig72DK4LTiPLwS4

### Update car by id
PATCH http://localhost:3000/api/v1/cars/18
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidGVsZWdyYW1JZCI6IjEyMzIxMzkiLCJ1c2VySWQiOjIwLCJpYXQiOjE3Mzc5MjY0ODYsImV4cCI6MTczNzkzMDA4Nn0.y1qbqZwFGp2sCeIqQpjeQze1col1UKcDzNjBKLtpeRU

{
  "year" : 2010,
  "miliage" : 28000
}

### Create service for a car
POST http://localhost:3000/api/v1/services/
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidGVsZWdyYW1JZCI6IjEyMzIxMzkiLCJ1c2VySWQiOjIwLCJpYXQiOjE3Mzg3MDI0MjcsImV4cCI6MTczODcwNjAyN30.KtMSRxgzOvCoJ-HU-6m0B_WeXnP7IhGG-EGbGnpRip8

{
  "carId" : 6,
  "serviceDate" : "2025-02-04",
  "mileage" : 28000,
  "location" : "Home", 
  "works" : [
    {
      "description" : "Change tires",
      "cost" : 40
    },
    {
      "description" : "Change wipers",
      "cost" : 0
    }
  ],
  "spareParts" : [
    {
      "name" : "Wiper blade",
      "number" : null,
      "quantity" : 2,
      "cost" : 50
    },
    {
      "name" : "Tyres",
      "number" : null,
      "quantity" : 4,
      "cost" : 920
    }
  ]
}

### Get service for a car
GET http://localhost:3000/api/v1/services/cars/6?limit=10
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidGVsZWdyYW1JZCI6IjEyMzIxMzkiLCJ1c2VySWQiOjIwLCJpYXQiOjE3NDAwODQxNDksImV4cCI6MTc0MDA4Nzc0OX0.4W-Ht6yNL7ccCsm75dU2HdcxzRJHig72DK4LTiPLwS4

{ }

### Delete service for a car
DELETE  http://localhost:3000/api/v1/services/2
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidGVsZWdyYW1JZCI6IjEyMzIxMzkiLCJ1c2VySWQiOjIwLCJpYXQiOjE3MzkyMjI3NjUsImV4cCI6MTczOTIyNjM2NX0.L0k9dbURwbb44K6zFl0nsayKwaKTfLmPLe7Y2tY6w0Y 

{ }

### Add work to the service
POST http://localhost:3000/api/v1/works/
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidGVsZWdyYW1JZCI6IjEyMzIxMzkiLCJ1c2VySWQiOjIwLCJpYXQiOjE3Mzk0ODIzNDgsImV4cCI6MTczOTQ4NTk0OH0.jMP4GnoWsFNdT4qmMAf4dF2cOXrlaoyqJ9uyq8vqKN8

{
  "serviceId" : 5,
  "description" : "Add new line",
  "cost" : 100.0
}

### Delete work from the service
DELETE  http://localhost:3000/api/v1/works/13
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidGVsZWdyYW1JZCI6IjEyMzIxMzkiLCJ1c2VySWQiOjIwLCJpYXQiOjE3Mzk0ODIzNDgsImV4cCI6MTczOTQ4NTk0OH0.jMP4GnoWsFNdT4qmMAf4dF2cOXrlaoyqJ9uyq8vqKN8

{ }

### Add spare to the service
POST http://localhost:3000/api/v1/spares/
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidGVsZWdyYW1JZCI6IjEyMzIxMzkiLCJ1c2VySWQiOjIwLCJpYXQiOjE3Mzk0ODIzNDgsImV4cCI6MTczOTQ4NTk0OH0.jMP4GnoWsFNdT4qmMAf4dF2cOXrlaoyqJ9uyq8vqKN8

{
  "serviceId" : 5,
  "name" : "Add new line",
  "number" : "1234",
  "quantity" : 2, 
  "cost" : 100.0
}

### Delete work from the service
DELETE  http://localhost:3000/api/v1/spares/9
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidGVsZWdyYW1JZCI6IjEyMzIxMzkiLCJ1c2VySWQiOjIwLCJpYXQiOjE3Mzk0ODIzNDgsImV4cCI6MTczOTQ4NTk0OH0.jMP4GnoWsFNdT4qmMAf4dF2cOXrlaoyqJ9uyq8vqKN8

{ }